### ISSUE TITLE
Integrate ZKP Grant Phase1 RSA verification circuit into MynaWallet

### ISSUE THREAD

**Issue by motemotech** [MynaWallet/myna-wallet-monorepo#18]
### Describe the feature you would like

- [x] create a circuit
- [x] change [_validateSignature](https://github.com/MynaWallet/contracts/blob/cd431bae7d58a809ce1016d4a6b5f95f6c11f6de/src/base/MynaWallet.sol#L158) to zkp verification
- [x] deploy on testnet
- [x] conduct test using scripts
- [x] get gas benchmarks

### Circuit Overview
<img width="1269" alt="Screenshot 2023-10-22 at 21 28 12" src="https://github.com/MynaWallet/monorepo/assets/1129345/c04207a4-54ca-400d-b72f-81a6a41dd2bb">

- Create a circuit to demonstrate that RSA Signature Verification has been correctly executed.
- Generate identityCommitment from userSecret and modulus.
- Integrate the logic for on-chain verification of this into MynaWallet.
- Verify the gas cost at the time of executing a transaction.
- The proof system being utilized is Circom/Groth16.

**Comment by hiroism007** [comment]
#25 Merged and close.
