### ISSUE TITLE
Proposal to Integrate a Solidity Format to Enforce Code Formatting Standards

### ISSUE THREAD

**Issue by susumutomita** [MynaWallet/myna-wallet-monorepo#34]
### Describe the feature you would like

As our project grows, maintaining a consistent code formatting standard becomes crucial to ensure readability and to simplify the code review process. Implementing a `format_check` target in our Makefile that leverages Forge's formatting capabilities will help enforce our coding standards automatically.

## The primary goals of this issue

1. **Automate Code Formatting Verification**:
   - By adding a `format_check` target in our Makefile, we can automate the process of verifying that all Solidity contracts adhere to our project's coding standards. This automation will be particularly beneficial in identifying formatting issues early in the development process.

2. **Streamline Code Review Process**:
   - Automated formatting checks will streamline the code review process by reducing the manual effort required to check code formatting. This will allow reviewers to focus more on the logic and quality of the code, rather than formatting inconsistencies.

3. **Ensure Consistent Code Formatting**:
   - Consistent code formatting across all Solidity contracts will improve code readability and maintainability. It will also provide a more pleasant development experience, especially for developers new to the project.

4. **Ease of Use**:
   - With a simple `make format_check` command, developers can easily verify code formatting before committing changes, reducing the likelihood of formatting-related feedback during code reviews.

## Related Pull request 
https://github.com/MynaWallet/monorepo/pull/33

**Comment by motemotech** [comment]
merged.
